spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: sell
    password: sell
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell